# Generated by Django 3.2.7 on 2021-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('idcultivos', models.AutoField(db_column='idCultivos', primary_key=True, serialize=False)),
                ('nombrecultivo', models.CharField(blank=True, db_column='NombreCultivo', max_length=20, null=True)),
                ('alturamaxima', models.FloatField(blank=True, db_column='AlturaMaxima', null=True)),
                ('semanamax', models.IntegerField(blank=True, db_column='SemanaMax', null=True)),
                ('tasacresi', models.FloatField(blank=True, db_column='TasaCresi', null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('precioinicial', models.FloatField(blank=True, db_column='PrecioInicial', null=True)),
            ],
            options={
                'db_table': 'cultivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cultivosvsprocesos',
            fields=[
                ('idcultivovsproce', models.AutoField(db_column='idCultivoVsProce', primary_key=True, serialize=False)),
                ('cultivoscosechados', models.CharField(blank=True, db_column='CultivosCosechados', max_length=120, null=True)),
                ('precio', models.FloatField(blank=True, db_column='Precio', null=True)),
            ],
            options={
                'db_table': 'cultivosvsprocesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadocultivo',
            fields=[
                ('idestadocultivo', models.AutoField(db_column='idEstadoCultivo', primary_key=True, serialize=False)),
                ('nombredeestado', models.CharField(blank=True, db_column='NombreDeEstado', max_length=20, null=True)),
            ],
            options={
                'db_table': 'estadocultivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ofertademandaregistros',
            fields=[
                ('idofertademandaregistros', models.AutoField(db_column='idOfertaDemandaRegistros', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('preciototal', models.FloatField(blank=True, db_column='PrecioTotal', null=True)),
                ('producacum', models.FloatField(blank=True, db_column='ProducAcum', null=True)),
            ],
            options={
                'db_table': 'ofertademandaregistros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidasusuarios',
            fields=[
                ('idpartidasusuarios', models.AutoField(db_column='idPartidasUsuarios', primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(blank=True, db_column='Nombre_finca', max_length=45, null=True)),
                ('semanas', models.IntegerField(blank=True, db_column='Semanas', null=True)),
            ],
            options={
                'db_table': 'partidasusuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesoscultivos',
            fields=[
                ('codigo_cultivo', models.AutoField(db_column='CODIGO_Cultivo', primary_key=True, serialize=False)),
                ('agua', models.FloatField(blank=True, db_column='Agua', null=True)),
                ('semana', models.IntegerField(blank=True, db_column='Semana', null=True)),
                ('alturacultivo', models.FloatField(blank=True, db_column='AlturaCultivo', null=True)),
            ],
            options={
                'db_table': 'procesoscultivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrosdeentradassalidas',
            fields=[
                ('codigo_registro', models.AutoField(db_column='CODIGO_Registro', primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField(blank=True, db_column='Entrada', null=True)),
                ('salida', models.DateTimeField(blank=True, db_column='Salida', null=True)),
            ],
            options={
                'db_table': 'registrosdeentradassalidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(db_column='Nombre_usuario', max_length=20)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=45)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=45)),
                ('numero_celular', models.CharField(db_column='Numero_celular', max_length=15)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=50)),
                ('dataderegistro', models.DateTimeField(blank=True, db_column='DataDeRegistro', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
