-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 19:33:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`estadocultivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`estadocultivo` (
  `idEstadoCultivo` INT NOT NULL AUTO_INCREMENT,
  `NombreDeEstado` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstadoCultivo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`cultivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cultivos` (
  `idCultivos` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla Cultivos  para identificar cada fila.',
  `NombreCultivo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena el nombre del cultivo.',
  `AlturaMaxima` DOUBLE(6,2) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la altura maxima del cultivo para ecuaciones y procesos en el progama.',
  `SemanaMax` INT NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la semana maxima del cultivo para ecuaciones y procesos en el progama.',
  `TasaCresi` DOUBLE(6,2) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la tasa maxima del cultivo para ecuaciones y procesos en el progama.',
  `Cantidad` INT NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la cantidad del cultivo para ecuaciones y procesos en el progama.',
  `PrecioInicial` DOUBLE(6,2) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena el precio del cultivo para ecuaciones y procesos en el progama.',
  `EstadoCultivo_idEstadoCultivo` INT NOT NULL,
  PRIMARY KEY (`idCultivos`),
  INDEX `fk_Cultivos_EstadoCultivo1_idx` (`EstadoCultivo_idEstadoCultivo` ASC) VISIBLE,
  CONSTRAINT `fk_Cultivos_EstadoCultivo1`
    FOREIGN KEY (`EstadoCultivo_idEstadoCultivo`)
    REFERENCES `proyecto`.`estadocultivo` (`idEstadoCultivo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'El campo de la llaver primaria de la tabla, la cual es el identificador de las filas.',
  `Nombre_usuario` VARCHAR(20) NOT NULL COMMENT 'El campo en donde se almacena el nombre del tipo de usuario.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuarios` (
  `IDUsuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla Usuarios para identificar cada fila.',
  `Nombres` VARCHAR(45) NOT NULL COMMENT 'El campo que almacena el nombre del usuario.',
  `Apellidos` VARCHAR(45) NOT NULL COMMENT 'El campo que almacena el apellido del usuario.',
  `Numero_celular` VARCHAR(15) NOT NULL COMMENT 'El campo para almacenar el numero telefonico del usuario.\\n',
  `correo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena el correo del usuario.',
  `nombre_usuario` VARCHAR(20) NOT NULL COMMENT 'El campo en donde se almacena el nombreUsuario por el cual será buscado para el proceso de login.',
  `contraseña` VARCHAR(50) NOT NULL COMMENT 'El campo en donde se almacena la contraseña ya cifrada del usuario.',
  `DataDeRegistro` DATETIME NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la fecha y hora en que se registró.',
  `tipo_usuario_id` INT NOT NULL COMMENT 'El campo es una llave foranea de la tabla tipo_usuario, para clasificar que tipo de usuario es.\\n',
  `EstadoCultivo_idEstadoCultivo` INT NOT NULL,
  PRIMARY KEY (`IDUsuario`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  INDEX `fk_usuarios_EstadoCultivo1_idx` (`EstadoCultivo_idEstadoCultivo` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_EstadoCultivo1`
    FOREIGN KEY (`EstadoCultivo_idEstadoCultivo`)
    REFERENCES `proyecto`.`estadocultivo` (`idEstadoCultivo`),
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `proyecto`.`tipo_usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`partidasusuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`partidasusuarios` (
  `idPartidasUsuarios` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla PartidasUsuarios para identificar cada fila.',
  `usuarios_IDUsuario` INT NOT NULL COMMENT 'Es la llave foranea de la tabla usuarios para obtener la informacion del usuario.',
  `Nombre_finca` VARCHAR(45) NULL DEFAULT NULL,
  `Semanas` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPartidasUsuarios`),
  INDEX `fk_PartidasUsuarios_usuarios_idx` (`usuarios_IDUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_PartidasUsuarios_usuarios`
    FOREIGN KEY (`usuarios_IDUsuario`)
    REFERENCES `proyecto`.`usuarios` (`IDUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`procesoscultivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`procesoscultivos` (
  `CODIGO_Cultivo` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla ProcesosCultivos para identificar cada fila.',
  `Agua` DOUBLE(6,2) NULL DEFAULT NULL COMMENT 'El campo almacena la cantidad de agua que utiliza al momento de regar el cultivo.\\n',
  `Semana` INT NULL DEFAULT NULL COMMENT 'El campo en donde se guarda la semana que lleva el proceso del cultivo.',
  `AlturaCultivo` DOUBLE(6,2) NULL DEFAULT NULL COMMENT 'El campo en donde se almacena la altura que tiene en el proceso del cultivo.',
  `PartidasUsuarios_idPartidasUsuarios` INT NOT NULL COMMENT 'Es la llave forane de la tabla PartidasUsuarios para tener la informacion de la partida.',
  PRIMARY KEY (`CODIGO_Cultivo`),
  INDEX `fk_registrodepartidaporItera_PartidasProyecto_idx` (`PartidasUsuarios_idPartidasUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_registrodepartidaporItera_PartidasProyecto`
    FOREIGN KEY (`PartidasUsuarios_idPartidasUsuarios`)
    REFERENCES `proyecto`.`partidasusuarios` (`idPartidasUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 247
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`cultivosvsprocesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cultivosvsprocesos` (
  `idCultivoVsProce` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla CultivosVsProcesos  para identificar cada fila.',
  `Cultivos_idCultivos` INT NOT NULL COMMENT 'Es la llave foranea de la tabla Cultivos, para tener el identificador del cultivo.',
  `ProcesosCultivos_CODIGO_Cultivo` INT NOT NULL COMMENT 'Es la llave foranea de la tabla ProcesosCultivos, para tener un identificador de los procesos del  cultivo. ',
  `CultivosCosechados` VARCHAR(120) NULL DEFAULT NULL,
  `Precio` DOUBLE(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idCultivoVsProce`),
  INDEX `fk_CultivoVsProce_Cultivos1_idx` (`Cultivos_idCultivos` ASC) VISIBLE,
  INDEX `fk_CultivoVsProce_ProcesosCultivos1_idx` (`ProcesosCultivos_CODIGO_Cultivo` ASC) VISIBLE,
  CONSTRAINT `fk_CultivoVsProce_Cultivos1`
    FOREIGN KEY (`Cultivos_idCultivos`)
    REFERENCES `proyecto`.`cultivos` (`idCultivos`),
  CONSTRAINT `fk_CultivoVsProce_ProcesosCultivos1`
    FOREIGN KEY (`ProcesosCultivos_CODIGO_Cultivo`)
    REFERENCES `proyecto`.`procesoscultivos` (`CODIGO_Cultivo`))
ENGINE = InnoDB
AUTO_INCREMENT = 203
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`ofertademandaregistros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`ofertademandaregistros` (
  `idOfertaDemandaRegistros` INT NOT NULL AUTO_INCREMENT,
  `PartidasUsuarios_idPartidasUsuarios` INT NOT NULL COMMENT 'Es la llave foranea de la tabla PartidaUsuarios para tener un indicador de la partida.',
  `Cantidad` INT NULL DEFAULT NULL COMMENT 'El campo que almacena la cantidad de las ventas realizadas en la partida.',
  `PrecioTotal` DOUBLE(25,2) NULL DEFAULT NULL,
  `ProducAcum` DOUBLE(25,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idOfertaDemandaRegistros`),
  INDEX `fk_OfertaDemandaRegistros_PartidasProyecto_idx` (`PartidasUsuarios_idPartidasUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_OfertaDemandaRegistros_PartidasProyecto`
    FOREIGN KEY (`PartidasUsuarios_idPartidasUsuarios`)
    REFERENCES `proyecto`.`partidasusuarios` (`idPartidasUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`registrosdeentradassalidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`registrosdeentradassalidas` (
  `CODIGO_Registro` INT NOT NULL AUTO_INCREMENT COMMENT 'Es la llave principal de la tabla registrosDeEntradasSalidas para identificar cada fila.',
  `Entrada` DATETIME NULL DEFAULT NULL COMMENT 'Es un campo en donde se almacena la fecha y hora de entrada del usuario a la aplicación.',
  `Salida` DATETIME NULL DEFAULT NULL COMMENT 'Es un campo en donde se almacena la fecha y hora de salida del usuario a la aplicación.\\n',
  `usuarios_IDUsuario` INT NOT NULL COMMENT 'Es la llave foranea de la tabla Usuarios, para tener la informacion del usuario.',
  PRIMARY KEY (`CODIGO_Registro`),
  INDEX `fk_registrosDeEntradasSalidas_Proyecto_idx` (`usuarios_IDUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_registrosDeEntradasSalidas_Proyecto`
    FOREIGN KEY (`usuarios_IDUsuario`)
    REFERENCES `proyecto`.`usuarios` (`IDUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 830
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
